### ISSUE TITLE
Contact Details

### ISSUE THREAD

**Issue by SamKemp** [deggua/Halo-MCC-Map-Tools#1]
Hi @deggua I am interested in this project and am a programmer myself.
Do you have a contact where we can talk some more about this?

**Comment by Waffle1434** [comment]
I am also interested if anyone sees this. I've been using HxD to see the title and description, which was pretty easy.

However, there is some spooky action going on with the map content. After `mvar..p(....` object data seems to be stored... except it appears to be compressed or (very unlikely) encrypted. Changing 1 coordinate of an object results in a decent chunk of the data changing, instead of just a few bites if it we raw. Knowing how small map files typically were, this makes me think Bungie was compressing the map data.
